# 実験1:iPhoneの広角カメラで撮影した画像を用いてカメラキャリブレーションを行う

In [22]:
import numpy as np
import cv2
import glob

# チェッカーボードのパラメーター
CHECKERBOARD = (9, 9) 
# チェッカーボードサイズ（mm）
CHECKERBOARD_SIZE = 18

# キャリブレーション画像フォルダのパス
images_folder = 'camera_4.2/'

# チェッカーボードの3D座標
objp = np.zeros((CHECKERBOARD[0]*CHECKERBOARD[1], 3), np.float32)
objp[:,:2] = np.mgrid[0:CHECKERBOARD[0],0:CHECKERBOARD[1]].T.reshape(-1,2)*CHECKERBOARD_SIZE

# 3D座標と2D座標の対応を保存するための配列
objpoints = [] # 3D座標
imgpoints = [] # 2D座標

# キャリブレーション画像を読み込んで、チェッカーボードを検出する
images = glob.glob(images_folder + '*.JPG')
for fname in images:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    ret, corners = cv2.findChessboardCorners(gray, CHECKERBOARD, None)

    # チェッカーボードを検出した場合、3D座標と2D座標の対応を追加する
    if ret == True:
        objpoints.append(objp)
        imgpoints.append(corners)

# キャリブレーションを実行する
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

# 焦点距離、レンズ歪み、画像中心座標を表示する
print("Focal Length: ", mtx[0][0])
print("Distortion Coefficients: ", dist)
print("Image Center: ", mtx[0][2], mtx[1][2])

# 画像中心座標を取得
h, w = gray.shape[:2]
newcameramtx, roi = cv2.getOptimalNewCameraMatrix(mtx, dist, (w, h), 1, (w, h))
cx, cy = newcameramtx[0][2], newcameramtx[1][2]
print("\nPrincipal Point: ({}, {})".format(cx, cy))

# 内部パラメータの表示
print("Camera Matrix:\n", mtx)

Focal Length:  3059.144851637834
Distortion Coefficients:  [[ 2.23846990e-01 -7.14772132e-01 -1.10507210e-03  2.83078030e-04
   5.32659154e-01]]
Image Center:  1499.603394457762 2001.8495710815223

Principal Point: (1500.693420677926, 1996.4862571293488)
Camera Matrix:
 [[3.05914485e+03 0.00000000e+00 1.49960339e+03]
 [0.00000000e+00 3.05805845e+03 2.00184957e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]


# 実験2:iPhoneの超広角カメラを用いてカメラキャリブレーションを行う

In [23]:
import numpy as np
import cv2
import glob

# チェッカーボードのパラメーター
CHECKERBOARD = (9, 9) 
# チェッカーボードサイズ（mm）
CHECKERBOARD_SIZE = 18

# キャリブレーション画像フォルダのパス
images_folder = 'camera_1.55/'

# チェッカーボードの3D座標
objp = np.zeros((CHECKERBOARD[0]*CHECKERBOARD[1], 3), np.float32)
objp[:,:2] = np.mgrid[0:CHECKERBOARD[0],0:CHECKERBOARD[1]].T.reshape(-1,2)*CHECKERBOARD_SIZE

# 3D座標と2D座標の対応を保存するための配列
objpoints = [] # 3D座標
imgpoints = [] # 2D座標

# キャリブレーション画像を読み込んで、チェッカーボードを検出する
images = glob.glob(images_folder + '*.JPG')
for fname in images:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    ret, corners = cv2.findChessboardCorners(gray, CHECKERBOARD, None)

    # チェッカーボードを検出した場合、3D座標と2D座標の対応を追加する
    if ret == True:
        objpoints.append(objp)
        imgpoints.append(corners)

# キャリブレーションを実行する
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

# 焦点距離、レンズ歪み、画像中心座標を表示する
print("Focal Length: ", mtx[0][0])
print("Distortion Coefficients: ", dist)
print("Image Center: ", mtx[0][2], mtx[1][2])

# 画像中心座標を取得
h, w = gray.shape[:2]
newcameramtx, roi = cv2.getOptimalNewCameraMatrix(mtx, dist, (w, h), 1, (w, h))
cx, cy = newcameramtx[0][2], newcameramtx[1][2]
print("\nPrincipal Point: ({}, {})".format(cx, cy))

# 内部パラメータの表示
print("Camera Matrix:\n", mtx)

Focal Length:  1631.0714396341382
Distortion Coefficients:  [[ 0.01583644 -0.02517731 -0.00094901  0.00014359  0.0201964 ]]
Image Center:  1521.3525492776275 2014.3845519684546

Principal Point: (1521.6770387769066, 2009.0431455574726)
Camera Matrix:
 [[1.63107144e+03 0.00000000e+00 1.52135255e+03]
 [0.00000000e+00 1.62848883e+03 2.01438455e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
